# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@openai/codex-0.107.0" = {
      name = "_at_openai_slash_codex";
      packageName = "@openai/codex";
      version = "0.107.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@openai/codex/-/codex-0.107.0.tgz";
        sha512 = "bAHmp4I3YNEqeR5U+LA5yViecDTlLVAJ+EGo8h647f0DClEWxFtyKXzyBJQ/kcL1G3bzstOTcuVpTdjhvJoe6g==";
      };
    };
    "@openai/codex-darwin-arm64-npm:@openai/codex@0.107.0-darwin-arm64" = {
      name = "_at_openai_slash_codex-darwin-arm64";
      packageName = "@openai/codex-darwin-arm64";
      version = "npm:@openai/codex@0.107.0-darwin-arm64";
      src = fetchurl {
        url = "https://registry.npmjs.org/@openai/codex/-/codex-0.107.0-darwin-arm64.tgz";
        sha512 = "g8u0nsns9JaHNYehVuw1eSL/83BSuBsmdOo2rrEU0D1rKI/QoIQSv6S6offZnQFerCHeqj0LabxYzqUTBzEh0g==";
      };
    };
    "@openai/codex-darwin-x64-npm:@openai/codex@0.107.0-darwin-x64" = {
      name = "_at_openai_slash_codex-darwin-x64";
      packageName = "@openai/codex-darwin-x64";
      version = "npm:@openai/codex@0.107.0-darwin-x64";
      src = fetchurl {
        url = "https://registry.npmjs.org/@openai/codex/-/codex-0.107.0-darwin-x64.tgz";
        sha512 = "uDCfszYS/9RL6fMBqnLyFloBCa/Lgvqjt/P2izrByRANlHZG4Nwn1Sayn7v2TugvOJ5fBPZMRcaloqfjowmdEQ==";
      };
    };
    "@openai/codex-linux-arm64-npm:@openai/codex@0.107.0-linux-arm64" = {
      name = "_at_openai_slash_codex-linux-arm64";
      packageName = "@openai/codex-linux-arm64";
      version = "npm:@openai/codex@0.107.0-linux-arm64";
      src = fetchurl {
        url = "https://registry.npmjs.org/@openai/codex/-/codex-0.107.0-linux-arm64.tgz";
        sha512 = "iAPYuXfACBSjVf4DPkN8YFawFGXPORzm7hDJhkzqqQvXRSyeZDaVkdT81FhaNIjm1rcaMnMDGJn2M+tOwmGy0w==";
      };
    };
    "@openai/codex-linux-x64-npm:@openai/codex@0.107.0-linux-x64" = {
      name = "_at_openai_slash_codex-linux-x64";
      packageName = "@openai/codex-linux-x64";
      version = "npm:@openai/codex@0.107.0-linux-x64";
      src = fetchurl {
        url = "https://registry.npmjs.org/@openai/codex/-/codex-0.107.0-linux-x64.tgz";
        sha512 = "h9SG15CrNihjHwSiYBU3dxMWH2r9fQIBPxFIpWnSUnjE5/YaXusbJQEvC+5u+g6CzUXX40fFsm3gVWV9uzX7Og==";
      };
    };
    "@openai/codex-win32-arm64-npm:@openai/codex@0.107.0-win32-arm64" = {
      name = "_at_openai_slash_codex-win32-arm64";
      packageName = "@openai/codex-win32-arm64";
      version = "npm:@openai/codex@0.107.0-win32-arm64";
      src = fetchurl {
        url = "https://registry.npmjs.org/@openai/codex/-/codex-0.107.0-win32-arm64.tgz";
        sha512 = "LHGQA2h/L72NRFcdIjKN/+V2nFXfuHDSQcI1Qdt9/7fUdcpb/pqN1n7U5rujccuTCf0ihk4XhGywAwiwPsjmWA==";
      };
    };
    "@openai/codex-win32-x64-npm:@openai/codex@0.107.0-win32-x64" = {
      name = "_at_openai_slash_codex-win32-x64";
      packageName = "@openai/codex-win32-x64";
      version = "npm:@openai/codex@0.107.0-win32-x64";
      src = fetchurl {
        url = "https://registry.npmjs.org/@openai/codex/-/codex-0.107.0-win32-x64.tgz";
        sha512 = "Iq1UOxj2El/syo8abN0/7Z6ICIVTW7tY9DJbdx01wjQYbi6Ecb8e66iTNFq65Mingq7vG7QWvYGyLycVztHFuw==";
      };
    };
  };
  args = {
    name = "node-global";
    packageName = "node-global";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@openai/codex-0.107.0"
      sources."@openai/codex-darwin-arm64-npm:@openai/codex@0.107.0-darwin-arm64"
      sources."@openai/codex-darwin-x64-npm:@openai/codex@0.107.0-darwin-x64"
      sources."@openai/codex-linux-arm64-npm:@openai/codex@0.107.0-linux-arm64"
      sources."@openai/codex-linux-x64-npm:@openai/codex@0.107.0-linux-x64"
      sources."@openai/codex-win32-arm64-npm:@openai/codex@0.107.0-win32-arm64"
      sources."@openai/codex-win32-x64-npm:@openai/codex@0.107.0-win32-x64"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
